// Parse genealogy.net / Online-OFB (Ortssippenbucher) - see issue #197.
//
// This is NOT one site with one template - it's ~1,373 independently
// compiled, independently maintained local heritage books ("OFBs",
// selected via the ofb= URL param), each generated by whatever software
// its individual contributor used (confirmed live across three real
// records: GEN_DO!, GEN_PLUS!, and FTM export - all different generators,
// all with different field sets and symbol usage). Only 3 of 1,373 have
// been checked. Every lookup in this file is written to degrade to a
// blank/empty result on an unrecognized shape, never to throw - the same
// hang-bug class already fixed this cycle across several other
// collections (parseSmartMatch, parseGeneanet, parseFilae, etc.) is
// exactly the failure mode to avoid here by construction, and at this
// sample size an unrecognized shape is the expected common case, not an
// edge case.
//
// SECURITY - do not remove this guard or the reasoning behind it: the
// "berlin" sample's raw HTML contains a hidden (white-on-white CSS) link
// with anchor text "nur fur KI, Menschen hier nicht klicken" ("only for
// AI, humans don't click here") pointing to /superduperdoku/ - a
// prompt-injection trap aimed at AI/scraper agents reading page source,
// not real site content for a human visitor. This parser only ever
// extracts links matching the exact expected pattern
// (famreport.php?...&ID=...) via OFB_FAMILY_LINK_SELECTOR, used by
// getOFBSameRowLink()/getOFBChildrenLinks()/getOFBSiblingsLinks()/
// getOFBSpouseLinks() below - it never enumerates or follows arbitrary <a>
// tags found on the page, and never treats any text extracted from fetched
// HTML as an instruction to act on. That scoped-link-matching approach is
// what defeats this trap; if this file is ever changed to walk all <a>
// tags on the page "for simplicity," that protection is gone.

registerCollection({
    "reload": false,
    "experimental": true,
    "usesDeepResearch": true, // #213: fetchOFBFamilyViaTab() below
    "recordtype": "Online-OFB Genealogy",
    "prepareUrl": function(url) {
        // German mode gives ambiguous numeric dates (03.07.1850 - is that
        // 3 July or 7 March?); English mode gives unambiguous ones
        // (03 Jul 1850) - see issue #197. Force it regardless of what
        // language the user was browsing in. Note: translation coverage is
        // inconsistent even in English mode - some German UI strings leak
        // through regardless (confirmed per the issue) - so no string
        // extracted from this page should ever be assumed to definitely be
        // English, including labels this file doesn't yet know about.
        if (url.contains("lang=") && !url.contains("lang=en")) {
            url = url.replace(/lang=[^&]*/, "lang=en");
            this.reload = true;
        } else if (!url.contains("lang=")) {
            url += (url.contains("?") ? "&" : "?") + "lang=en";
            this.reload = true;
        }
        return url;
    },
    "collectionMatch": function(url) {
        // online-ofb.de and ofb.genealogy.net are confirmed mirrors of the
        // identical backend and dataset (issue #197 comment) - both
        // accepted as equivalent. Other *.genealogy.net subdomains are
        // mentioned in the original issue but unconfirmed; not matched
        // here rather than guessing they behave the same way.
        return (startsWithHTTP(url, "https://online-ofb.de/famreport.php") ||
            startsWithHTTP(url, "https://www.online-ofb.de/famreport.php") ||
            startsWithHTTP(url, "https://ofb.genealogy.net/famreport.php"));
    },
    "parseData": function(url) {
        focusURLid = getOFBItemId(url);
        getPageCode();
    },
    "loadPage": function(request) {
        if (isOFBChallengePage(request.source)) {
            // The user's own tab already solved Anubis to get here in the
            // first place (this is the initial page load, not a recursive
            // family-member fetch) - reaching a challenge page here would
            // mean something unexpected, not the normal case. Leave
            // focusname unset rather than guessing; parseOnlineOFB's own
            // guard handles the family-member-fetch version of this.
            return;
        }
        var parsed = $(request.source.replace(/<img /ig, "<track "));
        focusname = getOFBName(parsed, tablink);
    },
    "parseProfileData": parseOnlineOFB
});

// Best-effort marker check for Anubis's proof-of-work challenge page
// (issue #197: "Making sure you're not a bot!") - the exact page text
// isn't independently confirmed here, only reported secondhand, so this
// checks a few plausible variants rather than one exact string. Used to
// distinguish "this fetch got challenged, retry via tab" from "this is a
// genuinely sparse but real profile" in getOFBFamily() below - if this
// check has false negatives (challenge page not recognized), the fallback
// is only ever a blank/incomplete family member, never a hang or crash.
function isOFBChallengePage(htmlstring) {
    if (!exists(htmlstring)) {
        return false;
    }
    return /making sure you.?re not a bot|anubis/i.test(htmlstring);
}

function parseOnlineOFB(htmlstring, familymembers, relation) {
    if (!exists(htmlstring) || isOFBChallengePage(htmlstring)) {
        return "";
    }
    relation = relation || "";
    var parsed = $(htmlstring.replace(/<img /ig, "<track "));
    var cells = getOFBCells(parsed);

    var focusperson = getOFBName(parsed, relation.url || tablink);
    // A real "berlin" family report page has a male.gif/female.gif icon
    // directly next to the person's name (images/female.gif, confirmed
    // live) - read via getOFBGenderIcon() below. Falls back to "unknown"
    // if no icon is found, same as before this was confirmed; family
    // members below still separately get a relationship-based inference
    // (father/mother/etc.) when there's no icon to read for them either,
    // same fallback TNG/Geneanet already use.
    var genderval = getOFBGenderIcon(parsed);
    if (relation === "" ) {
        focusgender = genderval;
    } else if (genderval === "unknown" && exists(relation.gender) && relation.gender !== "unknown") {
        genderval = relation.gender;
    }

    $("#readstatus").html(escapeHtml(focusperson));

    var profiledata = {name: focusperson, gender: genderval, status: relation.title};

    profiledata["birth"] = getOFBDate(cells, OFB_BIRTH_LABELS);
    if (profiledata["birth"].length === 0) {
        // Baptism-only records use an explicit "Baptism:"/"Taufe:" label
        // instead of the birth symbol when there's no birth date at all
        // (confirmed live on the spandau sample) - fall back to it as the
        // best available date, same convention collections/tng.js and
        // several others already use for a missing birth date.
        profiledata["baptism"] = getOFBDate(cells, OFB_BAPTISM_LABELS);
    }
    // Death symbol set is NOT fully confirmed - only the religion-specific
    // ✡ (juden_nw) and burial ▭ (spandau, on a sibling) have actually been
    // seen live; a plain "†" is anticipated (the issue's own original
    // technical notes expected it, and it's the standard genealogical
    // death marker) but unconfirmed against a real record. Known gap,
    // flagged rather than silently assumed complete - see issue #197.
    profiledata["death"] = getOFBDate(cells, OFB_DEATH_LABELS);

    var about = "";
    // Misc free-text fields vary by generator and are all optional -
    // Religion:/Chronicle: (juden_nw), Godfather: (spandau), Ereignisse:/
    // Anmerkung: (berlin's FTM export). Folded into the about/notes text
    // rather than given dedicated profile fields, same treatment
    // collections/geneanet.js gives its own individual/family notes.
    OFB_MISC_TEXT_FIELDS.forEach(function (field) {
        var value = getOFBFieldText(cells, field.labels).replace(OFB_FOOTNOTE_PATTERN, "").trim();
        if (value !== "") {
            about += (about !== "" ? "\n" : "") + field.name + ": " + value;
        }
    });
    if (about.trim() !== "") {
        profiledata["about"] = about;
    }

    // Photo, when present - a jQuery "imagescroller" widget (confirmed
    // live on the juden_nw sample: a 135px gallery linking to the
    // full-size image, e.g. "./juden_nw/Bilder/I97113.jpg", resolved
    // against the page's own URL to get the absolute path). Not every
    // profile has one ("on 'some' profiles" per the user) - degrades to
    // no photo fields set when the widget isn't found. Takes only the
    // first photo if the scroller ever has more than one - SmartCopy's
    // own profile data model is a single thumb/image pair, not a gallery.
    var photoUrl = getOFBPhotoUrl(parsed, relation.url || tablink);
    if (photoUrl !== "") {
        profiledata["thumb"] = photoUrl;
        profiledata["image"] = photoUrl;
    }

    // Also the mechanism that correctly marks a privacy-redacted person
    // Living, with no Online-OFB-specific code needed here at all -
    // focusperson is OFB_PRIVACY_PLACEHOLDER ("<Private>") for one of
    // those, and checkLiving() already recognizes that exact prefix (see
    // OFB_PRIVACY_PLACEHOLDER's own comment above).
    if (checkLiving(focusperson)) {
        profiledata["alive"] = true;
    }

    if (familymembers) {
        loadGeniData();
        var famid = 0;
        // Parent sub-label (e.g. "Naturlich"/natural under Vater:/Mutter:)
        // noted in the issue's scoping request as present in at least one
        // sample, but its exact placement relative to the parent link
        // isn't confirmed - not implemented in this pass rather than
        // guessing at markup that could misparse the parent link itself,
        // which matters far more than the sub-label. Known gap.
        var father = getOFBParentLink(cells, OFB_FATHER_LABELS);
        if (father.length > 0) {
            processOFBFamily(father[0], "father", famid);
            famid++;
        }
        var mother = getOFBParentLink(cells, OFB_MOTHER_LABELS);
        if (mother.length > 0) {
            processOFBFamily(mother[0], "mother", famid);
            famid++;
        }
        var spouses = getOFBSpouseLinks(cells);
        // Attached to whichever spouse is processed first - with more than
        // one "Spouse:" row (unconfirmed live, but plausible - remarriage)
        // this would incorrectly apply the same marriage date to every
        // spouse, since getOFBMarriageDate() only reads the first matching
        // Spouse: cell. Known simplification, not guessed further without
        // a real multi-spouse sample to check against.
        var marriageDate = getOFBMarriageDate(cells);
        for (var s = 0; s < spouses.length; s++) {
            processOFBFamily(spouses[s], "spouse", famid, marriageDate);
            myhspouse.push(famid);
            famid++;
        }
        var children = getOFBChildrenLinks(cells);
        for (var c = 0; c < children.length; c++) {
            processOFBFamily(children[c], "child", famid);
            famid++;
        }
        var siblings = getOFBSiblingsLinks(cells);
        for (var sib = 0; sib < siblings.length; sib++) {
            processOFBFamily(siblings[sib], "sibling", famid);
            famid++;
        }
    } else if (isParent(relation.title)) {
        var childrensection = getOFBChildrenLinks(cells);
        for (var i = 0; i < childrensection.length; i++) {
            processOFBFamily(childrensection[i], "sibling", 0);
        }
    } else if (isChild(relation.title) || isSibling(relation.title)) {
        var parentIds = [];
        var f = getOFBParentLink(cells, OFB_FATHER_LABELS);
        if (f.length > 0) {
            var fid = getOFBItemId($(f[0]).attr("href"));
            if (fid !== "") {
                parentIds.push(fid);
            }
        }
        var m = getOFBParentLink(cells, OFB_MOTHER_LABELS);
        if (m.length > 0) {
            var mid = getOFBItemId($(m[0]).attr("href"));
            if (mid !== "") {
                parentIds.push(mid);
            }
        }
        if (isChild(relation.title)) {
            for (var p = 0; p < parentIds.length; p++) {
                if (focusURLid !== parentIds[p]) {
                    childlist[relation.proid] = $.inArray(parentIds[p], unionurls);
                    profiledata["parent_id"] = $.inArray(parentIds[p], unionurls);
                    break;
                }
            }
        } else if (parentIds.length > 0) {
            profiledata["halfsibling"] = !recursiveCompare(parentlist, parentIds);
        }
    }

    if (familymembers) {
        alldata["profile"] = profiledata;
        alldata["scorefactors"] = smscorefactors;
        updateGeo();
    }

    return profiledata;
}

var OFB_BIRTH_LABELS = ["✶", "Birth:", "Geburt:"];
var OFB_BAPTISM_LABELS = ["Baptism:", "Taufe:"];
// ✡ = Star of David (juden_nw, religion-specific), ▭ = burial
// symbol (spandau); "†" (dagger) added defensively per the issue's
// original expectation, not yet confirmed live - see the comment above
// this list's only call site.
var OFB_DEATH_LABELS = ["✡", "▭", "†", "Death:", "Tod:"];
var OFB_FATHER_LABELS = ["Father:", "Vater:"];
var OFB_MOTHER_LABELS = ["Mother:", "Mutter:"];
// Per-row label, present only when a spouse actually exists (confirmed on
// both full real samples - when there's no spouse, there's no "Spouse:"
// label anywhere on the page at all, just the group header below and the
// empty-state text - see getOFBSpouseLinks()). "Partner:" is a fourth
// generator's wording for the same row (the "kempen" OFB, exported from
// AGES software - confirmed live, and present verbatim even with &lang=en
// forced, since &lang=en only translates the surrounding site chrome/group
// headers, not every book generator's own field labels - see prepareUrl's
// comment above and OFB_FATHER_LABELS/OFB_MOTHER_LABELS, which already
// carry both languages for the same reason).
var OFB_SPOUSE_LABELS = ["Spouse:", "Spouses:", "Ehegatte:", "Ehegatten:", "Partner:", "Partners:"];
// Group header only - confirmed on both full real samples that there is no
// per-row "Children:"/"Siblings:" label at all, only these two-column
// section headers ("Marriages / Partnerships" | "Children",
// "Parents" | "Siblings"). Kept the old colon-suffixed forms too in case a
// different generator does use a simpler flat label - tried as an
// additional variant, not instead of the confirmed header text.
var OFB_MARRIAGES_HEADER_LABELS = ["Marriages / Partnerships"];
var OFB_CHILDREN_LABELS = ["Children", "Children:", "Kinder", "Kinder:"];
var OFB_SIBLING_LABELS = ["Siblings", "Siblings:", "Geschwister", "Geschwister:"];
// Free-text fields, all generator-specific and all optional.
var OFB_MISC_TEXT_FIELDS = [
    {"name": "Religion", "labels": ["Religion:"]},
    {"name": "Chronicle", "labels": ["Chronicle:", "Chronik:"]},
    {"name": "Godfather", "labels": ["Godfather:", "Pate:", "Patin:"]},
    {"name": "Events", "labels": ["Ereignisse:"]},
    {"name": "Notes", "labels": ["Anmerkung:"]},
    {"name": "Occupation", "labels": ["Occupation:", "Beruf:"]}
];
// Empty-relationship states render as explicit text rather than an omitted
// row (issue #197) - recognized here so a genuinely empty section reads as
// "confirmed empty," not a parse failure worth flagging. Functionally both
// cases already produce zero entries either way (getOFBFamilyLinks()
// degrades to [] regardless), so this only affects the console.warn below,
// not correctness.
var OFB_EMPTY_MARKERS = {
    "spouse": ["No spouse found!", "Kein Ehegatte gefunden!"],
    "children": ["No children found!", "Keine Kinder gefunden!"],
    // "No siblings found!" (English) confirmed live on the "berlin" sample -
    // the original English variant list here only had the German text.
    "siblings": ["No siblings found!", "Keine Geschwister gefunden!"]
};

// Cell-by-cell text is used for label matching (getOFBFieldText/
// getOFBFieldCell below) rather than the page's full concatenated text,
// since jQuery's .text() on a large fragmented-table page runs every
// cell's content together with no separator - a label and an unrelated
// later value could otherwise get matched as if adjacent. The DOM
// elements themselves (not just their text) are kept in this array so
// getOFBFamilyLinks() can search each match's containing <table> for the
// <a> links belonging to that field.
function getOFBCells(parsed) {
    return parsed.find("td").toArray();
}

// Returns {index, text, remainder} for the first cell matching any of the
// given label/symbol variants, or null if none match - every field this is
// used for is optional across the ~1,373 independently-generated OFBs.
function getOFBFieldCell(cells, variants) {
    for (var v = 0; v < variants.length; v++) {
        var variant = variants[v];
        for (var i = 0; i < cells.length; i++) {
            var cellText = $(cells[i]).text().trim();
            if (cellText.indexOf(variant) === 0) {
                var remainder = cellText.substring(variant.length).replace(/^[:\s]+/, "").trim();
                return {"index": i, "text": cellText, "remainder": remainder};
            }
        }
    }
    return null;
}

// Two lookup strategies, tried in order, since there's no single
// consistent label/value layout across generators (confirmed by the three
// live samples): the label and value can share one cell ("Birth: 03 Jul
// 1850"), or the label can sit alone with the value in a following cell -
// the pattern collections/tng.js's getTNGField() relies on exclusively,
// also confirmed present here. That second case isn't always the
// *immediate* next cell, though - a real live sample (a "berlin" family
// report page) has an empty spacer <td width=3></td> between the ✶ symbol
// and its actual date value, which broke birth/death/baptism extraction
// entirely (father/mother still worked, since those labels apparently
// aren't followed by a spacer). Scan forward past empty cells instead of
// checking only the one immediately after the label - bounded to a few
// cells so this can't wander into an unrelated later field on a page with
// no spacer at all.
var OFB_FORWARD_SCAN_LIMIT = 3;
function getOFBFieldText(cells, variants) {
    var match = getOFBFieldCell(cells, variants);
    if (!exists(match)) {
        return "";
    }
    if (match.remainder !== "") {
        return match.remainder;
    }
    for (var offset = 1; offset <= OFB_FORWARD_SCAN_LIMIT && match.index + offset < cells.length; offset++) {
        var next = $(cells[match.index + offset]).text().trim();
        if (next !== "") {
            return next;
        }
    }
    return "";
}

// Date+place format confirmed live on a real "berlin" sample: "06 May 1873
// in Friedrichshagen,  Berlin,  Deutschland" (English) / "06.05.1873 in
// Friedrichshagen,  Berlin,  Deutschland" (German - same " in " connector
// either way, since German "in" happens to be identical to English "in"
// here). The place itself commonly has its own internal commas (city,
// region, country), so splitting on the first comma the way most other
// collections in this codebase do was wrong here - it cut "Friedrichshagen"
// off the date side and left the place truncated. Split on " in " instead;
// only fall back to a first-comma split if " in " isn't present, for
// whatever other date-only-with-comma shape a different generator might
// use. Degrades to a date-only result if neither pattern applies, never
// throws.
function getOFBDate(cells, variants) {
    var raw = getOFBFieldText(cells, variants);
    if (raw === "") {
        return [];
    }
    return parseOFBDateString(raw);
}

// Source-citation footnote markers (confirmed live: "06 Jan 1860 in
// Schroda [1]", the "[1]" referencing a "Sources" list elsewhere on the
// page, and again on a misc field: "1846 Metzger in Darfeld [1]") - shared
// so both a date value (parseOFBDateString below) and a misc free-text
// field (OFB_MISC_TEXT_FIELDS' loop in parseOnlineOFB) strip it the same
// way, rather than leaving it dangling only on the fields someone happened
// to test against a footnoted sample first.
var OFB_FOOTNOTE_PATTERN = /\s*\[\s*\d+\s*\]\s*$/;

// Shared by getOFBDate() (looks up a labeled cell first) and
// getOFBMarriageDate() below (extracts a symbol-marked segment out of a
// cell that mixes several dates together) - everything past "found the
// raw date+place text" is identical between them.
function parseOFBDateString(raw) {
    var data = [];
    if (raw === "") {
        return data;
    }
    // Stripped from the raw string up front so this also covers a footnote
    // with no place at all (e.g. a bare "1813 [1]").
    raw = raw.replace(OFB_FOOTNOTE_PATTERN, "").trim();
    // German circa/relative-date words - confirmed live: "um 1840 in
    // Drensteinfurt" ("um" = "about"). Raw field text can't be assumed
    // English even with &lang=en forced (see prepareUrl's own comment), so
    // this translates to the same English markers cleanDate()
    // (buildform.js, shared across every collection) already recognizes
    // ("ABT"/"about" -> "Circa", etc.), rather than teaching that shared
    // function a new language for one collection's benefit. Anchored to the
    // start of the string, matching where these words actually appear
    // (immediately before the year) rather than replacing anywhere in the
    // string, which could otherwise mangle an unrelated place name later in
    // the same value.
    raw = raw.replace(/^um\s+/i, "Circa ")
        .replace(/^vor\s+/i, "Before ")
        .replace(/^nach\s+/i, "After ")
        .replace(/^zwischen\s+/i, "Between ");
    // "zwischen X und Y" only had its leading keyword translated above -
    // the "und" (German "and") connector was left as-is. Downstream
    // "Between X and Y" consumers (checkBurial() in buildform.js, and
    // popup.js's own date-submission logic) split on the literal string
    // " and ", so an untranslated "und" left the whole range unparsed
    // instead of yielding just the end date. Scoped to right after
    // "Between " (not a blind global replace) so an unrelated "und"
    // elsewhere in the string - if one ever appeared - isn't mangled.
    if (raw.startsWith("Between ")) {
        raw = raw.replace(" und ", " and ");
    }
    var datepart = raw;
    var placepart = "";
    var inIndex = raw.indexOf(" in ");
    if (inIndex !== -1) {
        datepart = raw.substring(0, inIndex).trim();
        placepart = raw.substring(inIndex + 4).trim();
    } else if (raw.contains(",")) {
        var split = raw.split(",");
        datepart = split[0].trim();
        placepart = split.slice(1).join(",").trim();
    }
    datepart = cleanDate(datepart);
    if (datepart !== "") {
        data.push({date: datepart});
    }
    if (placepart !== "") {
        // Collapse the multi-space runs the raw markup has between
        // comma-separated place components (e.g. "Friedrichshagen,  Berlin,
        // Deutschland" - two spaces after each comma in the real sample)
        // down to a single space, for a cleaner display value.
        placepart = placepart.replace(/\s+/g, " ").replace(/\s*,\s*/g, ", ").trim();
        data.push({id: geoid, location: placepart});
        geoid++;
    }
    return data;
}

// Marriage date/place, marked with the ⚭ symbol - confirmed live embedded
// directly inside the Spouse: value cell, alongside the spouse's own
// birth (✶) and death (✡) dates, all <br>-separated within that one cell
// (e.g. "Emanuel WOLFF<br>✶ 03 Jul 1850 in Posen<br>✡ 30 Dec 1901 in
// Berlin<br>⚭ 27 Jan 1880 in Posen (StA) [1]"). jQuery's .text() doesn't
// preserve <br> as a separator, so the whole cell collapses to one run-on
// string with no boundary between segments - the symbols themselves are
// what mark where each one starts, so this splits on those rather than
// relying on <br>.
var OFB_MARRIAGE_SYMBOL = "⚭";
function getOFBMarriageDate(cells) {
    var spouseMatch = getOFBFieldCell(cells, OFB_SPOUSE_LABELS);
    if (!exists(spouseMatch)) {
        return [];
    }
    var valueCell = $(cells[spouseMatch.index]).next("td");
    if (valueCell.length === 0) {
        return [];
    }
    var text = valueCell.text();
    var marriageIndex = text.indexOf(OFB_MARRIAGE_SYMBOL);
    if (marriageIndex === -1) {
        return [];
    }
    var afterSymbol = text.substring(marriageIndex + OFB_MARRIAGE_SYMBOL.length);
    var otherSymbols = ["✶", "✡", "▭", "†"];
    var nextSymbolIndex = -1;
    otherSymbols.forEach(function (symbol) {
        var idx = afterSymbol.indexOf(symbol);
        if (idx !== -1 && (nextSymbolIndex === -1 || idx < nextSymbolIndex)) {
            nextSymbolIndex = idx;
        }
    });
    var raw = (nextSymbolIndex === -1 ? afterSymbol : afterSymbol.substring(0, nextSymbolIndex)).trim();
    return parseOFBDateString(raw);
}

// Every family-member link this file extracts goes through this one
// pattern (see the file-level SECURITY comment at the top - this parser
// never enumerates or follows arbitrary <a> tags found on the page).
var OFB_FAMILY_LINK_SELECTOR = 'a[href*="famreport.php"]';

// Father/Mother/Spouse: on both full real pages checked, the value (when
// present) is the single <td> immediately following the label's own cell,
// in the same row. Deliberately takes only that ONE next cell, not a
// wider same-row scan - Father's row also has a third cell (Siblings'
// value, see getOFBSiblingsLinks() below) that a broader scan would
// wrongly fold into Father's own result.
//
// An earlier version of this function scoped to the label's closest
// ancestor <table> instead. That was wrong: Father: and Mother: turned out
// to sit as adjacent rows within one large shared grid table (which also
// holds Marriages/Partnerships, Children, Parents, and Siblings), so both
// labels' "closest table" resolved to that same big table, and both
// lookups returned the same first link found in it - reported live as
// "mother" showing a duplicate of "father." This function - and the
// row-based ones below it - replace that with the structure actually
// confirmed live.
function getOFBSameRowLink(labelCell) {
    var next = $(labelCell).next("td");
    if (next.length === 0) {
        return [];
    }
    return next.find(OFB_FAMILY_LINK_SELECTOR).toArray();
}

// Father/Mother: single expected match, single link.
function getOFBParentLink(cells, labelVariants) {
    var match = getOFBFieldCell(cells, labelVariants);
    if (!exists(match)) {
        return [];
    }
    return getOFBSameRowLink(cells[match.index]);
}

// Spouse: unlike Father/Mother, more than one "Spouse:" row is plausible
// (remarriage) even though neither confirmed sample happens to show it -
// collects every matching label's same-row link rather than assuming
// exactly one. When there's no spouse at all, there is no "Spouse:" label
// anywhere on the page (confirmed live - the empty case renders as
// "No spouse found!" directly, with no per-row label) - checked via
// OFB_MARRIAGES_HEADER_LABELS + getOFBGridValueRow() instead, purely to
// decide whether an unrecognized-shape warning is worth logging, since
// either way the functional result is already the same empty list.
function getOFBSpouseLinks(cells) {
    var links = [];
    for (var i = 0; i < cells.length; i++) {
        var cellText = $(cells[i]).text().trim();
        var isSpouseLabel = OFB_SPOUSE_LABELS.some(function (label) {
            return cellText.indexOf(label) === 0;
        });
        if (isSpouseLabel) {
            links = links.concat(getOFBSameRowLink(cells[i]));
        }
    }
    if (links.length === 0) {
        var valueRow = getOFBGridValueRow(cells, OFB_MARRIAGES_HEADER_LABELS);
        if (exists(valueRow)) {
            var recognized = OFB_EMPTY_MARKERS.spouse.some(function (marker) {
                return valueRow.text().contains(marker);
            });
            if (!recognized) {
                console.warn("SmartCopy: Online-OFB spouse section found no links and no recognized empty-state text - possibly an unrecognized page shape.");
            }
        }
    }
    return links;
}

// Children: no per-row "Children:" label was found on either confirmed
// real sample, only the "Children" group header (paired with "Marriages /
// Partnerships" in the same header row). The value - or the "No children
// found!"/"Keine Kinder gefunden!" empty-state text - is always the LAST
// <td> in the row immediately following that header row, regardless of
// how many cells precede it: 3 cells (Spouse: label, spouse value,
// children value) when there's a spouse, 2 cells ("No spouse found!",
// children value/empty-text) when there isn't. Confirmed on both full
// real samples either way.
function getOFBChildrenLinks(cells) {
    var valueRow = getOFBGridValueRow(cells, OFB_CHILDREN_LABELS);
    if (!exists(valueRow)) {
        return [];
    }
    var lastCell = valueRow.find("td").last();
    if (lastCell.length === 0) {
        return [];
    }
    var links = lastCell.find(OFB_FAMILY_LINK_SELECTOR).toArray();
    if (links.length === 0) {
        var recognized = OFB_EMPTY_MARKERS.children.some(function (marker) {
            return lastCell.text().contains(marker);
        });
        if (!recognized) {
            console.warn("SmartCopy: Online-OFB children section found no links and no recognized empty-state text - possibly an unrecognized page shape.");
        }
    }
    return links;
}

// Siblings: same situation as Children - no per-row "Siblings:" label
// confirmed, only the "Siblings" group header (paired with "Parents").
// Unlike Children, though, the value isn't in the row right after the
// header - it's a ROWSPAN=2 cell that's visually beside both the Father
// and Mother rows, but structurally is the LAST <td> of Father's row
// specifically (confirmed on both full real samples). Depends on Father's
// own row being found first; if a profile ever omits the Father: row
// entirely for an unknown father (rather than showing it empty), this
// won't find the siblings value either - not confirmed either way from
// the samples checked so far.
function getOFBSiblingsLinks(cells) {
    var father = getOFBFieldCell(cells, OFB_FATHER_LABELS);
    if (!exists(father)) {
        return [];
    }
    var fatherRow = $(cells[father.index]).closest("tr");
    var lastCell = fatherRow.find("td").last();
    if (lastCell.length === 0) {
        return [];
    }
    var links = lastCell.find(OFB_FAMILY_LINK_SELECTOR).toArray();
    if (links.length === 0) {
        var recognized = OFB_EMPTY_MARKERS.siblings.some(function (marker) {
            return lastCell.text().contains(marker);
        });
        if (!recognized) {
            console.warn("SmartCopy: Online-OFB siblings section found no links and no recognized empty-state text - possibly an unrecognized page shape.");
        }
    }
    return links;
}

// Shared by getOFBSpouseLinks()/getOFBChildrenLinks() - finds a two-column
// grid section's header row (matching any of the given header label
// variants) and returns the very next sibling <tr>, which is where that
// section's actual value or empty-state text lives on both confirmed real
// samples. Returns null (not a throw) if the header isn't found or has no
// following row.
function getOFBGridValueRow(cells, headerLabelVariants) {
    var header = getOFBFieldCell(cells, headerLabelVariants);
    if (!exists(header)) {
        return null;
    }
    var headerRow = $(cells[header.index]).closest("tr");
    var valueRow = headerRow.next("tr");
    return valueRow.length > 0 ? valueRow : null;
}

// Confirmed live on a real "berlin" family report page: a male.gif/
// female.gif icon sits directly next to the person's name (as a <track>
// by the time this runs - see the <img>-to-<track> substitution at the
// top of parseOnlineOFB()/loadPage(), which exists specifically so this
// icon's attributes survive parsing instead of being stripped). Matches
// on the src filename rather than an alt attribute, since none was
// present in the confirmed sample. Takes the FIRST such icon found on the
// page - fine for the focus person's own top-of-page icon, but if a
// family-report-style page ever shows multiple people's icons together,
// this could pick up the wrong one; not something the current samples
// have shown a case for, so not guarded against yet.
function getOFBGenderIcon(parsed) {
    var icon = parsed.find('track[src*="female"], track[src*="male"]').first();
    if (icon.length === 0) {
        return "unknown";
    }
    return (icon.attr("src") || "").toLowerCase().contains("female") ? "female" : "male";
}

// Finds the first photo link inside a ".imagescroller" widget (the <a> tag
// wrapping the thumbnail, not the <track>-substituted <img> itself - the
// href and src point to the same file in the confirmed sample, and the
// <a> survives this file's <img>-to-<track> substitution untouched, so
// reading it avoids depending on that substitution having happened first).
// Resolved against `url` (the page's own URL) to turn the relative path
// ("./juden_nw/Bilder/I97113.jpg") into an absolute one. Returns "" - not
// a throw - if there's no scroller, no link, or the href doesn't resolve.
function getOFBPhotoUrl(parsed, url) {
    var link = parsed.find(".imagescroller a[href]").first();
    if (link.length === 0) {
        return "";
    }
    var href = link.attr("href");
    if (!exists(href) || href === "") {
        return "";
    }
    try {
        return new URL(href, url).href;
    } catch (error) {
        return "";
    }
}

// Two different name display conventions confirmed live so far, order
// varies by generator: "SURNAME, Given" (comma-separated - the issue's
// original technical notes) and "Given SURNAME" with no comma at all, the
// surname distinguished only by being in caps (confirmed live on real
// "berlin"/"juden_nw" family report pages: "Madchen MAASS"/"Hedwig WOLFF",
// inside a <FONT> tag - not covered by the original b/h1/h2/strong
// candidate list, which is why the name went blank before this was
// covered even though father/mother were found). OFB_SURNAME_PATTERN
// finds the all-caps run regardless of which side of the name it's on, so
// this doesn't assume a fixed order.
var OFB_SURNAME_PATTERN = /\b[A-ZÀ-ÖØ-Þ]{2,}\b/;

// A person's own identity can be privacy-REDACTED rather than merely
// missing - confirmed live on a real profile
// (famreport.php?ofb=deutsch_rasselwitz&ID=I27550): the name section sits
// in the exact same <font size="+1"> spot a real name would occupy, but
// literally reads "[Datenschutz]" (identical text in both lang=de and
// lang=en - it's the German word for "privacy/data protection," never
// translated). Before this was recognized, getOFBName()'s candidate loop
// below correctly skipped that literal text (no comma, no ALL-CAPS surname
// run for OFB_SURNAME_PATTERN to match) but then kept scanning and matched
// the NEXT b/h1/h2/strong/font candidate that happened to look
// name-shaped - which on a family report page is reliably the FATHER's own
// name, a few candidates further down in the Parents section. Confirmed
// live end-to-end: fetching this exact privacy-protected person as a
// family member (parseOnlineOFB() calls getOFBName() again on their own
// fetched page, same as any other family member) duplicated their own
// father's full name onto them as if it were their own. Recognizing the
// marker explicitly is required - merely adding it to the "doesn't match"
// filter isn't enough, since skipping it alone still falls through to the
// wrong next candidate.
var OFB_PRIVACY_MARKER = "[Datenschutz]";

// What getOFBName() returns instead, once OFB_PRIVACY_MARKER is recognized -
// deliberately NOT "" (blank/unknown). A privacy-redacted profile is a
// stronger, more useful signal than "we found nothing": (1) it's still
// worth a distinguishable placeholder so the row/dropdown option isn't
// literally blank and unreviewable, requested live after the fix that
// stopped the father's-name duplication left this case looking empty, and
// (2) German genealogy sites only ever privacy-redact people presumed
// still LIVING (deceased individuals' data isn't restricted the same way),
// so the redaction itself is a reliable "Living" signal, not a guess.
// "<Private>" (not "[Private]" or any other new wording) specifically
// reuses this codebase's OWN pre-existing convention for exactly this
// concept - collections/smartmatch.js already uses the identical literal
// string for a SmartMatch-redacted candidate, and checkLiving() (buildform.js)
// already recognizes a name starting with "<Private>" (or bare "Private")
// as a living-person signal. Using the same string means
// parseOnlineOFB()'s existing `if (checkLiving(focusperson))` check below
// picks this up for free - no new living/vital-specific code needed here.
// Verified via NameParse.parse("<Private>", ...): parses cleanly to
// firstName "<Private>", lastName "" - lands in First Name exactly as
// intended, nothing spills into Last Name.
var OFB_PRIVACY_PLACEHOLDER = "<Private>";

// Name display isn't confirmed to use a literal "Name:" label across all
// samples - tries the label lookup first, falls back to the page's first
// bold/header/font text that looks like a name (comma-separated, or has a
// caps-surname run) if that fails, and falls back again to the raw
// nachname= URL param alone if even that comes up empty. Never returns
// something that throws downstream; "" is a valid (if unhelpful) result
// like every other lookup in this file.
//
// Returns a PLAIN "Given Surname" string, matching every other collection
// in this codebase (collections/geneanet.js, wikitree.js, rootsweb.js,
// etc. all just space-join given+surname with no wrapping) - an earlier
// version of this function wrapped the surname in parens ("Given
// (SURNAME)"), copying collections/tng.js's own convention without
// checking what it actually means downstream. Verified directly against
// parse-names.js's NameParse.parse(): "(...)" specifically signals a
// *separate* birth/maiden name ("Mary Smith (Jones)" - married name
// Smith, maiden name Jones - see parse-names.js's own comment at that
// check), not "this is the surname." "Hedwig (WOLFF)" parsed to
// lastName: "" / birthName: "Wolff" - the actual last name came out
// empty, and "Wolff" would have been submitted to Geni's maiden-name
// field instead of the last-name field. Plain "Hedwig WOLFF" (still
// all-caps, no parens) correctly parses to lastName: "Wolff" - fix_case()
// already title-cases it, so no manual case conversion is needed here.
function getOFBName(parsed, url) {
    var cells = getOFBCells(parsed);
    var raw = getOFBFieldText(cells, ["Name:"]);
    if (raw === OFB_PRIVACY_MARKER) {
        return OFB_PRIVACY_PLACEHOLDER;
    }
    if (raw === "") {
        var candidates = parsed.find("b, h1, h2, strong, font").toArray();
        for (var i = 0; i < candidates.length; i++) {
            var text = $(candidates[i]).text().trim();
            if (text === OFB_PRIVACY_MARKER) {
                return OFB_PRIVACY_PLACEHOLDER;
            }
            if (text.length < 80 && (text.contains(",") || OFB_SURNAME_PATTERN.test(text))) {
                raw = text;
                break;
            }
        }
    }
    if (raw !== "" && raw.contains(",")) {
        var parts = raw.split(",");
        var surname = parts[0].trim();
        var given = parts.slice(1).join(",").trim();
        return given + " " + surname;
    }
    if (raw !== "") {
        var surnameMatch = raw.match(OFB_SURNAME_PATTERN);
        if (exists(surnameMatch)) {
            var capsSurname = surnameMatch[0];
            var restOfName = (raw.substring(0, surnameMatch.index) + raw.substring(surnameMatch.index + capsSurname.length)).trim();
            if (restOfName !== "") {
                return restOfName + " " + capsSurname;
            }
        }
        return raw;
    }
    var nachname = exists(url) ? getParameterByName("nachname", url) : "";
    return nachname || "";
}

function processOFBFamily(link, title, famid, marriageDate) {
    var url = $(link).attr("href");
    if (!exists(url) || url === "") {
        return;
    }
    if (!exists(alldata["family"][title])) {
        alldata["family"][title] = [];
    }
    var name = $(link).text().trim();
    // A privacy-redacted family member's link anchor text is itself the
    // literal "[Datenschutz]" placeholder (confirmed live - see
    // OFB_PRIVACY_MARKER above) - normalize it to the same
    // OFB_PRIVACY_PLACEHOLDER ("<Private>") here too, at the very first
    // point it's captured, not just in getOFBName()'s own deeper per-member
    // fetch. Keeps this initial value consistent with whatever the deeper
    // fetch will independently arrive at (same marker, same placeholder),
    // and specifically avoids leaving the literal German "[Datenschutz]"
    // text sitting in updateInfoData()'s "linked profile turned out blank,
    // fall back to the search summary's name" rule - that fallback only
    // ever fires on a genuinely blank name, so it never triggers once this
    // is normalized to a non-blank placeholder either way.
    if (name === OFB_PRIVACY_MARKER) {
        name = OFB_PRIVACY_PLACEHOLDER;
    }
    var itemid = getOFBItemId(url);
    var fullurl = new URL(url, tablink).href;
    var gendersv = "unknown";
    if (isFemale(title)) {
        gendersv = "female";
    } else if (isMale(title)) {
        gendersv = "male";
    } else if (isPartner(title)) {
        gendersv = reverseGender(focusgender);
    }
    if (isSibling(title)) {
        if (itemid !== focusURLid && siblinglist.indexOf(itemid) === -1) {
            siblinglist.push(itemid);
        } else {
            return;
        }
    } else if (isParent(title)) {
        parentlist.push(itemid);
    }
    var subdata = {name: name, title: title, gender: gendersv, url: fullurl, itemId: itemid, profile_id: famid};
    if (isPartner(title) && exists(marriageDate) && marriageDate.length > 0) {
        subdata["marriage"] = marriageDate;
    }
    unionurls[famid] = itemid;
    getOFBFamily(famid, fullurl, subdata);
}

// Only counts as usable if it actually produced a date - name alone
// doesn't distinguish a real (but date-sparse) record from an Anubis
// challenge page that still happened to yield some text, same convention
// collections/geneanet.js uses for its own equivalent check.
function isUsableOFBPerson(person) {
    return exists(person) && person !== "" && (exists(person.birth) || exists(person.death) || exists(person.baptism));
}

function getOFBFamily(famid, url, subdata) {
    familystatus.push(famid);
    fetchOFBPlain(url, subdata, function (person, arg, challenged) {
        if (isUsableOFBPerson(person)) {
            finishOFBFamilyMember(famid, person, arg);
            return;
        }
        if (!challenged) {
            // A real, parseable (if sparse) response that just isn't a
            // challenge page - nothing to gain from a tab retry.
            finishOFBFamilyMember(famid, person, arg);
            return;
        }
        // Anubis clearance, once earned by any one real tab this session,
        // is expected to carry over to plain fetches for other records too
        // (confirmed live per issue #197, same behavior already relied on
        // for Cloudflare in collections/geneanet.js) - retry the much
        // cheaper plain fetch once before falling back to another slow tab.
        if (ofbClearanceLikely) {
            fetchOFBPlain(url, subdata, function (retryPerson, retryArg, retryChallenged) {
                if (isUsableOFBPerson(retryPerson)) {
                    finishOFBFamilyMember(famid, retryPerson, retryArg);
                } else {
                    fetchOFBFamilyViaTab(famid, url, retryArg);
                }
            });
        } else {
            fetchOFBFamilyViaTab(famid, url, arg);
        }
    });
}

function fetchOFBPlain(url, subdata, callback) {
    chrome.runtime.sendMessage({
        method: "GET",
        action: "xhttp",
        variable: subdata,
        url: url,
        latency: 190
    }, function (response) {
        var arg = (exists(response) && exists(response.variable)) ? response.variable : subdata;
        var person = "";
        var challenged = false;
        if (exists(response) && exists(response.source)) {
            challenged = isOFBChallengePage(response.source);
            person = parseOnlineOFB(response.source, false, {"title": arg.title, "proid": arg.profile_id, "itemId": arg.itemId, "url": arg.url});
        }
        callback(person, arg, challenged);
    });
}

function finishOFBFamilyMember(famid, person, arg) {
    person = updateInfoData(person, arg);
    databyid[arg.profile_id] = person;
    alldata["family"][arg.title].push(person);
    familystatus.pop();
}

// Single-tab-at-a-time queue, same reasoning as
// collections/geneanet.js's equivalent: a burst of simultaneously-opened
// tabs is disruptive to watch and plausibly counterproductive against
// bot-detection, versus running the fallback for one person at a time.
var ofbTabQueue = [];
var ofbTabRunning = false;
// Set once any real tab gets past Anubis this session - see getOFBFamily().
var ofbClearanceLikely = false;

function fetchOFBFamilyViaTab(famid, url, arg) {
    ofbTabQueue.push({famid: famid, url: url, arg: arg});
    runNextOFBTabFetch();
}

function runNextOFBTabFetch() {
    if (!deepResearchOn || deepResearchSkipRun) {
        while (ofbTabQueue.length > 0) {
            var skipped = ofbTabQueue.shift();
            finishOFBFamilyMember(skipped.famid, "", skipped.arg);
        }
        return;
    }
    if (ofbTabRunning || ofbTabQueue.length === 0) {
        return;
    }
    ofbTabRunning = true;
    var next = ofbTabQueue.shift();
    runOFBTabFetch(next.famid, next.url, next.arg, function () {
        ofbTabRunning = false;
        runNextOFBTabFetch();
    });
}

function runOFBTabFetch(famid, url, arg, onDone) {
    $("#readstatus").html(escapeHtml(arg.name) + " (looking deeper, this may take a second)");
    chrome.tabs.create({url: url, active: false}, function (tab) {
        if (!exists(tab) || !exists(tab.id)) {
            finishOFBFamilyMember(famid, "", arg);
            onDone();
            return;
        }
        var settled = false;
        var attempts = 0;
        // Anubis's proof-of-work solve is confirmed live at ~5 seconds
        // (issue #197) - budgeted generously above that for a
        // Chrome-throttled background tab, matching the reasoning
        // collections/geneanet.js's own tab-fetch budget documents for the
        // same class of background-tab throttling.
        var maxAttempts = 10;

        function cleanupAndFinish(person) {
            if (settled) {
                return;
            }
            settled = true;
            var abortIndex = deepResearchInFlightAborts.indexOf(abortThisFetch);
            if (abortIndex !== -1) {
                deepResearchInFlightAborts.splice(abortIndex, 1);
            }
            chrome.tabs.remove(tab.id, function () {
                void chrome.runtime.lastError;
            });
            finishOFBFamilyMember(famid, person, arg);
            onDone();
        }

        function abortThisFetch() {
            cleanupAndFinish("");
        }
        deepResearchInFlightAborts.push(abortThisFetch);

        function attempt() {
            if (settled) {
                return;
            }
            attempts++;
            chrome.tabs.get(tab.id, function (tabInfo) {
                if (chrome.runtime.lastError || !exists(tabInfo)) {
                    cleanupAndFinish("");
                    return;
                }
                chrome.scripting.executeScript({
                    target: {tabId: tab.id},
                    func: function () {
                        var html = "", node = document.firstChild;
                        while (node) {
                            if (node.nodeType === Node.ELEMENT_NODE) {
                                html += node.outerHTML;
                            } else if (node.nodeType === Node.TEXT_NODE) {
                                html += node.nodeValue;
                            }
                            node = node.nextSibling;
                        }
                        return html;
                    }
                }, function (results) {
                    if (settled) {
                        return;
                    }
                    void chrome.runtime.lastError;
                    var html = (exists(results) && exists(results[0])) ? results[0].result : undefined;
                    if (exists(html) && !isOFBChallengePage(html)) {
                        ofbClearanceLikely = true;
                    }
                    var person = exists(html) ? parseOnlineOFB(html, false, {"title": arg.title, "proid": arg.profile_id, "itemId": arg.itemId, "url": arg.url}) : "";
                    if (isUsableOFBPerson(person) || attempts >= maxAttempts) {
                        cleanupAndFinish(person);
                    } else {
                        setTimeout(attempt, 1500);
                    }
                });
            });
        }
        setTimeout(attempt, 1500);
    });
}

// ofb= identifies which of the ~1,373 independent databases a record is
// in - ID alone is only unique within that one database (two different
// OFBs can both have an "I1"), same reasoning collections/tng.js's
// getTNGItemId() combines personID+tree for.
function getOFBItemId(url) {
    if (!exists(url) || url === "") {
        return "";
    }
    var ofb = getParameterByName("ofb", url);
    var id = getParameterByName("ID", url);
    return "ofb=" + ofb + "&ID=" + id;
}
