// Parse genealogy.net / Online-OFB (Ortssippenbucher) - see issue #197.
//
// This is NOT one site with one template - it's ~1,373 independently
// compiled, independently maintained local heritage books ("OFBs",
// selected via the ofb= URL param), each generated by whatever software
// its individual contributor used (confirmed live across three real
// records: GEN_DO!, GEN_PLUS!, and FTM export - all different generators,
// all with different field sets and symbol usage). Only 3 of 1,373 have
// been checked. Every lookup in this file is written to degrade to a
// blank/empty result on an unrecognized shape, never to throw - the same
// hang-bug class already fixed this cycle across several other
// collections (parseSmartMatch, parseGeneanet, parseFilae, etc.) is
// exactly the failure mode to avoid here by construction, and at this
// sample size an unrecognized shape is the expected common case, not an
// edge case.
//
// SECURITY - do not remove this guard or the reasoning behind it: the
// "berlin" sample's raw HTML contains a hidden (white-on-white CSS) link
// with anchor text "nur fur KI, Menschen hier nicht klicken" ("only for
// AI, humans don't click here") pointing to /superduperdoku/ - a
// prompt-injection trap aimed at AI/scraper agents reading page source,
// not real site content for a human visitor. This parser only ever
// extracts links matching the exact expected pattern
// (famreport.php?...&ID=...) via getOFBFamilyLinks() below - it never
// enumerates or follows arbitrary <a> tags found on the page, and never
// treats any text extracted from fetched HTML as an instruction to act
// on. That scoped-link-matching approach is what defeats this trap; if
// this file is ever changed to walk all <a> tags on the page "for
// simplicity," that protection is gone.

registerCollection({
    "reload": false,
    "experimental": true,
    "recordtype": "Online-OFB Genealogy",
    "prepareUrl": function(url) {
        // German mode gives ambiguous numeric dates (03.07.1850 - is that
        // 3 July or 7 March?); English mode gives unambiguous ones
        // (03 Jul 1850) - see issue #197. Force it regardless of what
        // language the user was browsing in. Note: translation coverage is
        // inconsistent even in English mode - some German UI strings leak
        // through regardless (confirmed per the issue) - so no string
        // extracted from this page should ever be assumed to definitely be
        // English, including labels this file doesn't yet know about.
        if (url.contains("lang=") && !url.contains("lang=en")) {
            url = url.replace(/lang=[^&]*/, "lang=en");
            this.reload = true;
        } else if (!url.contains("lang=")) {
            url += (url.contains("?") ? "&" : "?") + "lang=en";
            this.reload = true;
        }
        return url;
    },
    "collectionMatch": function(url) {
        // online-ofb.de and ofb.genealogy.net are confirmed mirrors of the
        // identical backend and dataset (issue #197 comment) - both
        // accepted as equivalent. Other *.genealogy.net subdomains are
        // mentioned in the original issue but unconfirmed; not matched
        // here rather than guessing they behave the same way.
        return (startsWithHTTP(url, "https://online-ofb.de/famreport.php") ||
            startsWithHTTP(url, "https://www.online-ofb.de/famreport.php") ||
            startsWithHTTP(url, "https://ofb.genealogy.net/famreport.php"));
    },
    "parseData": function(url) {
        focusURLid = getOFBItemId(url);
        getPageCode();
    },
    "loadPage": function(request) {
        if (isOFBChallengePage(request.source)) {
            // The user's own tab already solved Anubis to get here in the
            // first place (this is the initial page load, not a recursive
            // family-member fetch) - reaching a challenge page here would
            // mean something unexpected, not the normal case. Leave
            // focusname unset rather than guessing; parseOnlineOFB's own
            // guard handles the family-member-fetch version of this.
            return;
        }
        var parsed = $(request.source.replace(/<img[^>]*>/ig, ""));
        focusname = getOFBName(parsed, tablink);
    },
    "parseProfileData": parseOnlineOFB
});

// Best-effort marker check for Anubis's proof-of-work challenge page
// (issue #197: "Making sure you're not a bot!") - the exact page text
// isn't independently confirmed here, only reported secondhand, so this
// checks a few plausible variants rather than one exact string. Used to
// distinguish "this fetch got challenged, retry via tab" from "this is a
// genuinely sparse but real profile" in getOFBFamily() below - if this
// check has false negatives (challenge page not recognized), the fallback
// is only ever a blank/incomplete family member, never a hang or crash.
function isOFBChallengePage(htmlstring) {
    if (!exists(htmlstring)) {
        return false;
    }
    return /making sure you.?re not a bot|anubis/i.test(htmlstring);
}

function parseOnlineOFB(htmlstring, familymembers, relation) {
    if (!exists(htmlstring) || isOFBChallengePage(htmlstring)) {
        return "";
    }
    relation = relation || "";
    var parsed = $(htmlstring.replace(/<img[^>]*>/ig, ""));
    var cells = getOFBCells(parsed);

    var focusperson = getOFBName(parsed, relation.url || tablink);
    // No confirmed gender signal for the focus person specifically across
    // any of the three samples (no icon, no explicit field mentioned in
    // the issue or the live findings) - defaulting to "unknown" rather
    // than guessing from the name. Family members below DO get a
    // relationship-based inference, same fallback TNG/Geneanet already use
    // when they likewise have no direct signal to read.
    var genderval = "unknown";
    if (relation === "" ) {
        focusgender = genderval;
    } else if (exists(relation.gender) && relation.gender !== "unknown") {
        genderval = relation.gender;
    }

    $("#readstatus").html(escapeHtml(focusperson));

    var profiledata = {name: focusperson, gender: genderval, status: relation.title};

    profiledata["birth"] = getOFBDate(cells, OFB_BIRTH_LABELS);
    if (profiledata["birth"].length === 0) {
        // Baptism-only records use an explicit "Baptism:"/"Taufe:" label
        // instead of the birth symbol when there's no birth date at all
        // (confirmed live on the spandau sample) - fall back to it as the
        // best available date, same convention collections/tng.js and
        // several others already use for a missing birth date.
        profiledata["baptism"] = getOFBDate(cells, OFB_BAPTISM_LABELS);
    }
    // Death symbol set is NOT fully confirmed - only the religion-specific
    // ✡ (juden_nw) and burial ▭ (spandau, on a sibling) have actually been
    // seen live; a plain "†" is anticipated (the issue's own original
    // technical notes expected it, and it's the standard genealogical
    // death marker) but unconfirmed against a real record. Known gap,
    // flagged rather than silently assumed complete - see issue #197.
    profiledata["death"] = getOFBDate(cells, OFB_DEATH_LABELS);

    var about = "";
    // Misc free-text fields vary by generator and are all optional -
    // Religion:/Chronicle: (juden_nw), Godfather: (spandau), Ereignisse:/
    // Anmerkung: (berlin's FTM export). Folded into the about/notes text
    // rather than given dedicated profile fields, same treatment
    // collections/geneanet.js gives its own individual/family notes.
    OFB_MISC_TEXT_FIELDS.forEach(function (field) {
        var value = getOFBFieldText(cells, field.labels);
        if (value !== "") {
            about += (about !== "" ? "\n" : "") + field.name + ": " + value;
        }
    });
    if (about.trim() !== "") {
        profiledata["about"] = about;
    }

    if (checkLiving(focusperson)) {
        profiledata["alive"] = true;
    }

    if (familymembers) {
        loadGeniData();
        var famid = 0;
        // Parent sub-label (e.g. "Naturlich"/natural under Vater:/Mutter:)
        // noted in the issue's scoping request as present in at least one
        // sample, but its exact placement relative to the parent link
        // isn't confirmed - not implemented in this pass rather than
        // guessing at markup that could misparse the parent link itself,
        // which matters far more than the sub-label. Known gap.
        var father = getOFBFamilyLinks(cells, OFB_FATHER_LABELS, OFB_EMPTY_MARKERS.spouse);
        if (father.length > 0) {
            processOFBFamily(father[0], "father", famid);
            famid++;
        }
        var mother = getOFBFamilyLinks(cells, OFB_MOTHER_LABELS, OFB_EMPTY_MARKERS.spouse);
        if (mother.length > 0) {
            processOFBFamily(mother[0], "mother", famid);
            famid++;
        }
        var spouses = getOFBFamilyLinks(cells, OFB_SPOUSE_LABELS, OFB_EMPTY_MARKERS.spouse);
        for (var s = 0; s < spouses.length; s++) {
            processOFBFamily(spouses[s], "spouse", famid);
            myhspouse.push(famid);
            famid++;
        }
        var children = getOFBFamilyLinks(cells, OFB_CHILDREN_LABELS, OFB_EMPTY_MARKERS.children);
        for (var c = 0; c < children.length; c++) {
            processOFBFamily(children[c], "child", famid);
            famid++;
        }
        var siblings = getOFBFamilyLinks(cells, OFB_SIBLING_LABELS, OFB_EMPTY_MARKERS.siblings);
        for (var sib = 0; sib < siblings.length; sib++) {
            processOFBFamily(siblings[sib], "sibling", famid);
            famid++;
        }
    } else if (isParent(relation.title)) {
        var childrensection = getOFBFamilyLinks(cells, OFB_CHILDREN_LABELS, OFB_EMPTY_MARKERS.children);
        for (var i = 0; i < childrensection.length; i++) {
            processOFBFamily(childrensection[i], "sibling", 0);
        }
    } else if (isChild(relation.title) || isSibling(relation.title)) {
        var parentIds = [];
        var f = getOFBFamilyLinks(cells, OFB_FATHER_LABELS, OFB_EMPTY_MARKERS.spouse);
        if (f.length > 0) {
            var fid = getOFBItemId($(f[0]).attr("href"));
            if (fid !== "") {
                parentIds.push(fid);
            }
        }
        var m = getOFBFamilyLinks(cells, OFB_MOTHER_LABELS, OFB_EMPTY_MARKERS.spouse);
        if (m.length > 0) {
            var mid = getOFBItemId($(m[0]).attr("href"));
            if (mid !== "") {
                parentIds.push(mid);
            }
        }
        if (isChild(relation.title)) {
            for (var p = 0; p < parentIds.length; p++) {
                if (focusURLid !== parentIds[p]) {
                    childlist[relation.proid] = $.inArray(parentIds[p], unionurls);
                    profiledata["parent_id"] = $.inArray(parentIds[p], unionurls);
                    break;
                }
            }
        } else if (parentIds.length > 0) {
            profiledata["halfsibling"] = !recursiveCompare(parentlist, parentIds);
        }
    }

    if (familymembers) {
        alldata["profile"] = profiledata;
        alldata["scorefactors"] = smscorefactors;
        updateGeo();
    }

    return profiledata;
}

var OFB_BIRTH_LABELS = ["✶", "Birth:", "Geburt:"];
var OFB_BAPTISM_LABELS = ["Baptism:", "Taufe:"];
// ✡ = Star of David (juden_nw, religion-specific), ▭ = burial
// symbol (spandau); "†" (dagger) added defensively per the issue's
// original expectation, not yet confirmed live - see the comment above
// this list's only call site.
var OFB_DEATH_LABELS = ["✡", "▭", "†", "Death:", "Tod:"];
var OFB_FATHER_LABELS = ["Father:", "Vater:"];
var OFB_MOTHER_LABELS = ["Mother:", "Mutter:"];
var OFB_SPOUSE_LABELS = ["Spouse:", "Spouses:", "Ehegatte:", "Ehegatten:"];
var OFB_CHILDREN_LABELS = ["Children:", "Kinder:"];
var OFB_SIBLING_LABELS = ["Siblings:", "Geschwister:"];
// Free-text fields, all generator-specific and all optional.
var OFB_MISC_TEXT_FIELDS = [
    {"name": "Religion", "labels": ["Religion:"]},
    {"name": "Chronicle", "labels": ["Chronicle:", "Chronik:"]},
    {"name": "Godfather", "labels": ["Godfather:", "Pate:", "Patin:"]},
    {"name": "Events", "labels": ["Ereignisse:"]},
    {"name": "Notes", "labels": ["Anmerkung:"]}
];
// Empty-relationship states render as explicit text rather than an omitted
// row (issue #197) - recognized here so a genuinely empty section reads as
// "confirmed empty," not a parse failure worth flagging. Functionally both
// cases already produce zero entries either way (getOFBFamilyLinks()
// degrades to [] regardless), so this only affects the console.warn below,
// not correctness.
var OFB_EMPTY_MARKERS = {
    "spouse": ["No spouse found!", "Kein Ehegatte gefunden!"],
    "children": ["No children found!", "Keine Kinder gefunden!"],
    "siblings": ["Keine Geschwister gefunden!"]
};

// Cell-by-cell text is used for label matching (getOFBFieldText/
// getOFBFieldCell below) rather than the page's full concatenated text,
// since jQuery's .text() on a large fragmented-table page runs every
// cell's content together with no separator - a label and an unrelated
// later value could otherwise get matched as if adjacent. The DOM
// elements themselves (not just their text) are kept in this array so
// getOFBFamilyLinks() can search each match's containing <table> for the
// <a> links belonging to that field.
function getOFBCells(parsed) {
    return parsed.find("td").toArray();
}

// Returns {index, text, remainder} for the first cell matching any of the
// given label/symbol variants, or null if none match - every field this is
// used for is optional across the ~1,373 independently-generated OFBs.
function getOFBFieldCell(cells, variants) {
    for (var v = 0; v < variants.length; v++) {
        var variant = variants[v];
        for (var i = 0; i < cells.length; i++) {
            var cellText = $(cells[i]).text().trim();
            if (cellText.indexOf(variant) === 0) {
                var remainder = cellText.substring(variant.length).replace(/^[:\s]+/, "").trim();
                return {"index": i, "text": cellText, "remainder": remainder};
            }
        }
    }
    return null;
}

// Two lookup strategies, tried in order, since there's no single
// consistent label/value layout across generators (confirmed by the three
// live samples): the label and value can share one cell ("Birth: 03 Jul
// 1850"), or the label can sit alone with the value in the following cell
// - the pattern collections/tng.js's getTNGField() relies on exclusively,
// also confirmed present here.
function getOFBFieldText(cells, variants) {
    var match = getOFBFieldCell(cells, variants);
    if (!exists(match)) {
        return "";
    }
    if (match.remainder !== "") {
        return match.remainder;
    }
    if (match.index + 1 < cells.length) {
        var next = $(cells[match.index + 1]).text().trim();
        if (next !== "") {
            return next;
        }
    }
    return "";
}

// Date+place split is a best-effort heuristic (comma-separated, the most
// common convention elsewhere in this codebase) - not confirmed against a
// live Online-OFB date-with-place example, since neither the issue nor the
// three checked samples included one verbatim. Degrades to a date-only
// result if the split doesn't apply, never throws.
function getOFBDate(cells, variants) {
    var data = [];
    var raw = getOFBFieldText(cells, variants);
    if (raw === "") {
        return data;
    }
    var datepart = raw;
    var placepart = "";
    if (raw.contains(",")) {
        var split = raw.split(",");
        datepart = split[0].trim();
        placepart = split.slice(1).join(",").trim();
    }
    datepart = cleanDate(datepart);
    if (datepart !== "") {
        data.push({date: datepart});
    }
    if (placepart !== "") {
        data.push({id: geoid, location: placepart});
        geoid++;
    }
    return data;
}

// Finds every famreport.php family-member link within the closest <table>
// ancestor of a matched relationship label - scoped to that table (not the
// whole page) so an unrelated link elsewhere never gets pulled into the
// wrong relationship bucket, and bounded to exactly this link pattern (see
// the file-level SECURITY comment at the top - this is the one and only
// place this file extracts links from the page, deliberately never
// walking arbitrary <a> tags). Recognizes the site's own "no X found"
// text (OFB_EMPTY_MARKERS) as a confirmed-empty state; either way,
// degrades to [] rather than throwing when the section isn't found at all.
function getOFBFamilyLinks(cells, labelVariants, emptyMarkers) {
    var match = getOFBFieldCell(cells, labelVariants);
    if (!exists(match)) {
        return [];
    }
    var scope = $(cells[match.index]).closest("table");
    if (scope.length === 0) {
        scope = $(cells[match.index]).closest("tr");
    }
    var links = scope.find('a[href*="famreport.php"]').toArray();
    if (links.length === 0 && exists(emptyMarkers)) {
        var scopeText = scope.text();
        var recognized = emptyMarkers.some(function (marker) {
            return scopeText.contains(marker);
        });
        if (!recognized) {
            console.warn("SmartCopy: Online-OFB relationship section matched \"" + labelVariants[0] + "\" but has no links and no recognized empty-state text - possibly an unrecognized page shape.");
        }
    }
    return links;
}

// Name display isn't confirmed to use a literal "Name:" label across all
// three samples (the issue's own technical notes just describe the
// eventual "SURNAME, Given" shape, matching the url's own nachname= param
// as a cross-check) - tries the label lookup first, falls back to the
// page's first bold/header text containing a comma if that fails, and
// falls back again to the raw nachname= URL param alone if even that
// comes up empty. Never returns something that throws downstream; "" is a
// valid (if unhelpful) result like every other lookup in this file.
function getOFBName(parsed, url) {
    var cells = getOFBCells(parsed);
    var raw = getOFBFieldText(cells, ["Name:"]);
    if (raw === "") {
        var candidates = parsed.find("b, h1, h2, strong").toArray();
        for (var i = 0; i < candidates.length; i++) {
            var text = $(candidates[i]).text().trim();
            if (text.contains(",") && text.length < 80) {
                raw = text;
                break;
            }
        }
    }
    if (raw !== "" && raw.contains(",")) {
        var parts = raw.split(",");
        var surname = parts[0].trim();
        var given = parts.slice(1).join(",").trim();
        return given + " (" + surname + ")";
    }
    if (raw !== "") {
        return raw;
    }
    var nachname = exists(url) ? getParameterByName("nachname", url) : "";
    return nachname || "";
}

function processOFBFamily(link, title, famid) {
    var url = $(link).attr("href");
    if (!exists(url) || url === "") {
        return;
    }
    if (!exists(alldata["family"][title])) {
        alldata["family"][title] = [];
    }
    var name = $(link).text().trim();
    var itemid = getOFBItemId(url);
    var fullurl = new URL(url, tablink).href;
    var gendersv = "unknown";
    if (isFemale(title)) {
        gendersv = "female";
    } else if (isMale(title)) {
        gendersv = "male";
    } else if (isPartner(title)) {
        gendersv = reverseGender(focusgender);
    }
    if (isSibling(title)) {
        if (itemid !== focusURLid && siblinglist.indexOf(itemid) === -1) {
            siblinglist.push(itemid);
        } else {
            return;
        }
    } else if (isParent(title)) {
        parentlist.push(itemid);
    }
    var subdata = {name: name, title: title, gender: gendersv, url: fullurl, itemId: itemid, profile_id: famid};
    unionurls[famid] = itemid;
    getOFBFamily(famid, fullurl, subdata);
}

// Only counts as usable if it actually produced a date - name alone
// doesn't distinguish a real (but date-sparse) record from an Anubis
// challenge page that still happened to yield some text, same convention
// collections/geneanet.js uses for its own equivalent check.
function isUsableOFBPerson(person) {
    return exists(person) && person !== "" && (exists(person.birth) || exists(person.death) || exists(person.baptism));
}

function getOFBFamily(famid, url, subdata) {
    familystatus.push(famid);
    fetchOFBPlain(url, subdata, function (person, arg, challenged) {
        if (isUsableOFBPerson(person)) {
            finishOFBFamilyMember(famid, person, arg);
            return;
        }
        if (!challenged) {
            // A real, parseable (if sparse) response that just isn't a
            // challenge page - nothing to gain from a tab retry.
            finishOFBFamilyMember(famid, person, arg);
            return;
        }
        // Anubis clearance, once earned by any one real tab this session,
        // is expected to carry over to plain fetches for other records too
        // (confirmed live per issue #197, same behavior already relied on
        // for Cloudflare in collections/geneanet.js) - retry the much
        // cheaper plain fetch once before falling back to another slow tab.
        if (ofbClearanceLikely) {
            fetchOFBPlain(url, subdata, function (retryPerson, retryArg, retryChallenged) {
                if (isUsableOFBPerson(retryPerson)) {
                    finishOFBFamilyMember(famid, retryPerson, retryArg);
                } else {
                    fetchOFBFamilyViaTab(famid, url, retryArg);
                }
            });
        } else {
            fetchOFBFamilyViaTab(famid, url, arg);
        }
    });
}

function fetchOFBPlain(url, subdata, callback) {
    chrome.runtime.sendMessage({
        method: "GET",
        action: "xhttp",
        variable: subdata,
        url: url,
        latency: 190
    }, function (response) {
        var arg = (exists(response) && exists(response.variable)) ? response.variable : subdata;
        var person = "";
        var challenged = false;
        if (exists(response) && exists(response.source)) {
            challenged = isOFBChallengePage(response.source);
            person = parseOnlineOFB(response.source, false, {"title": arg.title, "proid": arg.profile_id, "itemId": arg.itemId, "url": arg.url});
        }
        callback(person, arg, challenged);
    });
}

function finishOFBFamilyMember(famid, person, arg) {
    person = updateInfoData(person, arg);
    databyid[arg.profile_id] = person;
    alldata["family"][arg.title].push(person);
    familystatus.pop();
}

// Single-tab-at-a-time queue, same reasoning as
// collections/geneanet.js's equivalent: a burst of simultaneously-opened
// tabs is disruptive to watch and plausibly counterproductive against
// bot-detection, versus running the fallback for one person at a time.
var ofbTabQueue = [];
var ofbTabRunning = false;
// Set once any real tab gets past Anubis this session - see getOFBFamily().
var ofbClearanceLikely = false;

function fetchOFBFamilyViaTab(famid, url, arg) {
    ofbTabQueue.push({famid: famid, url: url, arg: arg});
    runNextOFBTabFetch();
}

function runNextOFBTabFetch() {
    if (ofbTabRunning || ofbTabQueue.length === 0) {
        return;
    }
    ofbTabRunning = true;
    var next = ofbTabQueue.shift();
    runOFBTabFetch(next.famid, next.url, next.arg, function () {
        ofbTabRunning = false;
        runNextOFBTabFetch();
    });
}

function runOFBTabFetch(famid, url, arg, onDone) {
    $("#readstatus").html(escapeHtml(arg.name) + " (looking deeper, this may take a second)");
    chrome.tabs.create({url: url, active: false}, function (tab) {
        if (!exists(tab) || !exists(tab.id)) {
            finishOFBFamilyMember(famid, "", arg);
            onDone();
            return;
        }
        var settled = false;
        var attempts = 0;
        // Anubis's proof-of-work solve is confirmed live at ~5 seconds
        // (issue #197) - budgeted generously above that for a
        // Chrome-throttled background tab, matching the reasoning
        // collections/geneanet.js's own tab-fetch budget documents for the
        // same class of background-tab throttling.
        var maxAttempts = 10;

        function cleanupAndFinish(person) {
            if (settled) {
                return;
            }
            settled = true;
            chrome.tabs.remove(tab.id, function () {
                void chrome.runtime.lastError;
            });
            finishOFBFamilyMember(famid, person, arg);
            onDone();
        }

        function attempt() {
            if (settled) {
                return;
            }
            attempts++;
            chrome.tabs.get(tab.id, function (tabInfo) {
                if (chrome.runtime.lastError || !exists(tabInfo)) {
                    cleanupAndFinish("");
                    return;
                }
                chrome.scripting.executeScript({
                    target: {tabId: tab.id},
                    func: function () {
                        var html = "", node = document.firstChild;
                        while (node) {
                            if (node.nodeType === Node.ELEMENT_NODE) {
                                html += node.outerHTML;
                            } else if (node.nodeType === Node.TEXT_NODE) {
                                html += node.nodeValue;
                            }
                            node = node.nextSibling;
                        }
                        return html;
                    }
                }, function (results) {
                    if (settled) {
                        return;
                    }
                    void chrome.runtime.lastError;
                    var html = (exists(results) && exists(results[0])) ? results[0].result : undefined;
                    if (exists(html) && !isOFBChallengePage(html)) {
                        ofbClearanceLikely = true;
                    }
                    var person = exists(html) ? parseOnlineOFB(html, false, {"title": arg.title, "proid": arg.profile_id, "itemId": arg.itemId, "url": arg.url}) : "";
                    if (isUsableOFBPerson(person) || attempts >= maxAttempts) {
                        cleanupAndFinish(person);
                    } else {
                        setTimeout(attempt, 1500);
                    }
                });
            });
        }
        setTimeout(attempt, 1500);
    });
}

// ofb= identifies which of the ~1,373 independent databases a record is
// in - ID alone is only unique within that one database (two different
// OFBs can both have an "I1"), same reasoning collections/tng.js's
// getTNGItemId() combines personID+tree for.
function getOFBItemId(url) {
    if (!exists(url) || url === "") {
        return "";
    }
    var ofb = getParameterByName("ofb", url);
    var id = getParameterByName("ID", url);
    return "ofb=" + ofb + "&ID=" + id;
}
